import "@/styles/globals.css";
import {ClerkProvider} from "@clerk/nextjs";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { Toaster } from "sonner"

import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
  title: "GitChat",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <ClerkProvider>
            {children}
            <Toaster />
          </ClerkProvider>
        </TRPCReactProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
